# Starter pipeline
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'project.json'
    outputType: 'Process'
    orchestratorConnection: 'Azureconnexion'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    traceLevel: 'Information'


-trigger:
- main
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
